//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMC2021
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_Summary
    {
        public long id { get; set; }
        public string brand { get; set; }
        public string itemname { get; set; }
        public Nullable<long> unitsinstock { get; set; }
        public Nullable<long> unitsavailableforsale { get; set; }
        public Nullable<double> stockvalue { get; set; }
        public Nullable<double> saleprice { get; set; }
        public string barcode { get; set; }
    }
}
