//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMC2021
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lisensya
    {
        public long id { get; set; }
        public string pid { get; set; }
        public string ukey { get; set; }
        public string uname { get; set; }
        public string uemail { get; set; }
    }
}
