//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;


namespace BMC2021
{
    //using System.Data.Entity;
    //using System.Data.Entity.Infrastructure;

    public partial class POSDBEntities2 : DbContext
    {
      //  public POSDBEntities2(DbContextOptions<POSDBEntities2> options) : base(options)
       // { }

         public POSDBEntities2()
          // : base("name=POSDBEntities2")
           { }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            //NOTE! CHANGE THIS PATH PAG PACKING NA!
            //optionsBuilder.UseSqlite(@"Data Source=C:\Users\Frei\source\repos\BMC2021\POSDB.sqlite");
            // data source = "|DataDirectory|\bin\POSDB.sqlite"
            // optionsBuilder.UseSqlite(@"Data Source=|DataDirectory|\db\POSDB.sqlite");

            string baseDir = AppDomain.CurrentDomain.BaseDirectory;

            //if "bin" is present, remove all the path starting from "bin" word
            if (baseDir.Contains("bin"))
            {
                int index = baseDir.IndexOf("bin");
                baseDir = baseDir.Substring(0, index);
            }

            //String interpolation to reach the right 
            optionsBuilder.UseSqlite($"Data Source={baseDir}\\bin\\POSDB.sqlite");


        }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            // throw new UnintentionalCodeFirstException();

         //   modelBuilder.Entity<POSDBEntities2>().HasNoKey();
          //  modelBuilder.Entity<current_user>().HasNoKey();



        }
    
        public virtual DbSet<bprofile> bprofile { get; set; }
        public virtual DbSet<Reminder> Reminders { get; set; }
        public virtual DbSet<Inv_Peritem> Inv_Peritem { get; set; }
        public virtual DbSet<sales_customers> sales_customers { get; set; }
        public virtual DbSet<admin_users> admin_users { get; set; }
        public virtual DbSet<current_user> current_user { get; set; }
        public virtual DbSet<Inv_Summary> Inv_Summary { get; set; }
        public virtual DbSet<sales_peritem> sales_peritem { get; set; }
        public virtual DbSet<sales_pending_orders> sales_pending_orders { get; set; }
        
        public virtual DbSet<Lisensya> Lisensya { get; set; }
    }
}
