//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;


namespace BMC2021
{
    //using System;
    //using System.Data.Entity;
    //using System.Data.Entity.Infrastructure;

    public partial class POSDBEntities : DbContext
    {

      
        public POSDBEntities()
            //: base("name=POSDBEntities")
        {
        }
    
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            //throw new UnintentionalCodeFirstException();
        
    
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            string baseDir = AppDomain.CurrentDomain.BaseDirectory;

            //if "bin" is present, remove all the path starting from "bin" word
            if (baseDir.Contains("bin"))
            {
                int index = baseDir.IndexOf("bin");
                baseDir = baseDir.Substring(0, index);
            }

            //String interpolation to reach the right path
            optionsBuilder.UseSqlite($"Data Source={baseDir}\\bin\\POSDB.sqlite");

            //NOTE! CHANGE THIS PATH PAG PACKING NA!
            // optionsBuilder.UseSqlite(@"Data Source=|DataDirectory|\POSDB.sqlite");




        }

        public virtual DbSet<BPERSONNEL> BPERSONNELs { get; set; }
        public virtual DbSet<bprofile> bprofiles { get; set; }
    }
}
