//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMC2021
{
    using System;
    using System.Collections.Generic;
    
    public partial class sales_peritem
    {
       // public long sid { get; set; }
        public long id { get; set; }
        public string purchasedate { get; set; }
        public string barcode { get; set; }
        public string itembrand { get; set; }
        public string itemname { get; set; }
        public Nullable<double> purchaseprice { get; set; }
        public Nullable<double> finalsaleprice { get; set; }
        public Nullable<long> discount { get; set; }
        public string customername { get; set; }
        public Nullable<double> saleprice { get; set; }
        public string cashier { get; set; }
    }
}
